package e.pramu.sejarahkota;

import com.bumptech.glide.load.engine.Resource;

import java.util.ArrayList;

public class DataKota {

    private static String[] kotaNames = {
            "Jakarta",
            "Bali",
            "Banjarmasin",
            "Ambon",
            "Makassar",
            "Malang",
            "Surabaya",
            "Palembang",
            "Yogyakarta",
            "Medan"
    };

    private static String[] kotaDetails = {
            "Jakarta adalah ibu kota dan kota terbesar Indonesia. Terletak di estuari Sungai Ciliwung, di bagian barat laut Jawa, daerah ini telah lama menopang pemukiman manusia. Bukti bersejarah dari Jakarta berasal dari abad ke-4 M, saat ia merupakan sebuah permukiman dan pelabuhan Hindu. Kota ini telah diklaim secara berurutan oleh kerajaan bercorak India Tarumanegara, Kerajaan Sunda Hindu, Kesultanan Banten Muslim, dan oleh pemerintahan Belanda, Jepang, dan Indonesia. Hindia Belanda membangun daerah tersebut sebelum direbut oleh Kekaisaran Jepang semasa Perang Dunia II dan akhirnya menjadi merdeka sebagai bagian dari Indonesia.\n" +
                    "Jakarta telah dikenal dengan beberapa nama. Ia disebut Sunda Kelapa selama periode Kerajaan Sunda dan Jayakarta, Djajakarta, atau Jacatra selama periode singkat Kesultanan Banten. Setelah itu, Jakarta berkembang dalam tiga tahap. \"Kota Tua Jakarta\", yang dekat dengan laut di utara, berkembang antara 1619 dan 1799 pada era VOC. \"Kota baru\" di selatan berkembang antara 1809 dan 1942 setelah pemerintah Belanda mengambil alih penguasaan Batavia dari VOC yang gagal yang sewanya telah berakhir pada 1799. Yang ketiga adalah perkembangan Jakarta modern sejak proklamasi kemerdekaan pada 1945. Di bawah pemerintahan Belanda, ia dikenal sebagai Batavia (1619–1949), dan Djakarta (dalam bahasa Belanda) atau Jakarta, selama pendudukan Jepang dan masa modern.",
            "Bali telah dihuni oleh bangsa Austronesia sekitar tahun 2000 sebelum Masehi yang bermigrasi dan berasal dari Taiwan melalui Maritime Asia Tenggara. Budaya dan bahasa dari orang Bali demikian erat kaitannya dengan orang-orang dari kepulauan Indonesia, Malaysia, Filipina, dan Oseania. Alat-alat batu yang berasal dari saat itu telah ditemukan di dekat desa Cekik di sebelah barat pulau Bali.\n" +
                    "Pada tahun 1597 penjelajah Belanda yang bernama Cornelis de Houtman tiba di Bali dan dengan pembentukan Perusahaan India Timur Belanda pada tahun 1602, sebuah tempat didirikan untuk mengontrol kolonial dan dua setengah abad kemudian ketika pengontrolan dari pihak Belanda diperluas di seluruh Indonesia, kontrol politik dan ekonomi Belanda atas Bali dimulai pada tahun 1840-an di pantai utara pulau Bali, ketika itu Belanda mengadu domba antara kerajaan-kerajaan di Bali agar tidak percaya terhadap satu sama lain dan pada akhir 1890-an, perjuangan antara kerajaan Bali di selatan pulau Bali itu dimanfaatkan oleh Belanda untuk meningkatkan kendali mereka.\n" +
                    "Belanda melakukan serangan angkatan laut dan darat besar-besaran di wilayah Sanur pada tahun 1906 dan bertemu dengan ribuan anggota keluarga kerajaan dan para pengikut mereka yang berjuang melawan pasukan Belanda dengan serangan defensif bunuh diri (puputan) yang dilakukan oleh anggota keluarga kerajaan dan ribuan pengikut mereka daripada menghadapi penghinaan menyerah dari Belanda.\n" +
                    "Sekitar lebih dari 1.000 orang Bali meninggal pada saat itu melawan penjajah. Dalam intervensi Belanda di Bali pada tahun 1908, pembantaian serupa terjadi dalam menghadapi serangan Belanda di Klungkung. Setelah itu gubernur Belanda mampu melakukan kontrol administratif atas pulau Bali, tetapi kontrol lokal atas agama dan budaya umumnya tetap utuh.\n" +
                    "Pada tahun 1930-an, antropolog Margaret Mead dan Gregory Bateson, dan seniman Miguel Covarrubias dan Walter Spies, dan musikolog Colin McPhee menciptakan citra barat tentang Bali sebagai \"tanah terpesona yang damai dengan diri mereka sendiri dan alam\", dan pariwisata Barat pertama kali dikembangkan di pulau Bali pada saat itu.\n" +
                    "Imperial Jepang menduduki Bali selama Perang Dunia II. Pulau Bali awalnya bukan target dalam Kampanye Hindia Belanda mereka, tetapi karena lapangan terbang di Kalimantan yang tidak beroperasi karena hujan lebat tentara Kekaisaran Jepang memutuskan untuk menduduki Bali, yang tidak memiliki cuaca yang sebanding seperti Kalimantan.\n" +
                    "Pulau Bali pada saat itu tidak memiliki tentara Royal Netherlands East Indies Army (KNIL), yang ada hanyalah Native Auxiliary Corps Prajoda (Korps Prajoda) yang terdiri dari sekitar 600 tentara asli dan beberapa petugas Belanda KNIL di bawah komando Letkol KNIL WP Roodenburg. Pada tanggal 19 Februari 1942 pasukan Jepang mendarat di dekat Sanur.\n" +
                    "Pulau Bali cepat dikuasai oleh Jepang, selama pendudukan Jepang perwira militer Bali I Gusti Ngurah Rai, membentuk Bali 'bebas tentara'. Kurangnya perubahan kelembagaan dari waktu pemerintahan Belanda dan kerasnya permintaan resmi perang membuat pemerintahan Jepang sedikit lebih baik dari Belanda. Setelah Jepang menyerah di Pasifik pada bulan Agustus 1945, Belanda kembali ke Indonesia termasuk Bali dan segera ingin mengembalikan administrasi sebelum perang kolonial mereka.\n" +
                    "Hal ini ditentang oleh para pemberontak Bali yang pada saat itu sudah menggunakan senjata dari Jepang. Pada tanggal 20 November 1946, Pertempuran terjadi di Marga Tabanan di Bali tengah. Kolonel I Gusti Ngurah Rai, saat itu berusia 29 tahun, akhirnya membawa pasukannya ke Marga Rana, di mana mereka membuat serangan bunuh diri ke pihak Belanda yang bersenjata. Pasukan batalion Bali seluruhnya dihapus oleh Belanda, menghancurkan perlawanan terakhir dari perlawanan militer Bali.\n" +
                    "Pada tahun 1946 Belanda menjadikan Bali sebagai salah satu dari 13 wilayah administratif dari negara bagian yang baru diproklamasikan oleh Indonesia Timur, lawan dari negara Republik Indonesia yang diproklamasikan dan dipimpin oleh Soekarno dan Hatta. Bali masuk dalam \"Republik Indonesia\" ketika Belanda mengakui kemerdekaan Indonesia pada 29 Desember 1949.",
            "Banjarmasin adalah nama kampung yang dihuni suku Melayu. Kampung ini terletak di bagian utara muara sungai Kuin, yaitu kawasan Kelurahan Kuin Utara dan Alalak Selatan saat ini. Kampung Banjarmasih terbentuk oleh lima aliran sungai kecil, yaitu sungai Sipandai, sungai Sigaling, sungai Keramat, sungai Jagabaya dan sungai Pangeran yang semuanya bertemu membentuk sebuah danau. Kata banjar berasal dari bahasa Melayu yang berarti kampung atau juga berarti berderet-deret sebagai letak perumahan kampung berderet sepanjang tepian sungai. Banjarmasih berarti kampung orang-orang Melayu, sebutan dari dari orang Ngaju (suku Barangas) yang menghuni kampung-kampung sekitarnya.\n" +
                    "Penduduk Banjarmasih dikenal sebagai Oloh Masih yang artinya orang Melayu, sebutan oleh Oloh Ngaju (oloh = orang, ngaju = hulu) tersebut. Pemimpin masyarakat Oloh Masih disebut Patih Masih yang nama sebenarnya tidak diketahui. Menurut Hikayat Banjar, ketika menjadi ibu kota kerajaan (1520), Banjarmasin memiliki pelabuhan perdagangan yang disebut Bandar yang letaknya di tepi sungai Martapura di sebelah hulu dari muara sungai Kelayan",
            "Ambon adalah sebuah kota yang menjadi ibu kota Provinsi Maluku, Indonesia, berkelangsungan selama lima abad. Pada mulanya, Pulau Ambon didiami oleh suku Ambon yang berasal dari Pulau Seram di sisi utara pulau. Cikal bakal Kota Ambon mulai ada setelah datangnya para penjelajah Portugis ke Maluku pada 1513. Setelah itu, muncullah berbagai perkampungan yang terus menerus berkembang hingga menjadi Kota Ambon seperti sekarang.\n" +
                    "Kota ini diincar oleh bangsa Eropa karena andalan ekonominya yang berupa perdagangan rempah-rempah. Dengan demikian, terjadi berbagai pengalihan kekuasaan, mulai dari Portugal, Belanda, dan Britania Raya. Kota ini dijadikan kota pada tahun 1926 dengan dibentuknya Jabatan Wali Kota Ambon setelah sebelumnya langsung dibawahi oleh pemerintahan Gubernur Jenderal para penjajah. Sejak itu, kota ini berkembang pesat hingga menjadi kota terbesar dan termaju di Indonesia Timur seperti saat ini. Kota ini pun menikmati pertumbuhan ekonomi pesat setelah memiliki pemerintahan kotanya sendiri.\n" +
                    "Asal-usul dari istilah Ambon tidak mudah ditentukan. Menurut keterangan yang diberikan penduduk setempat, istilah tersebut berasal dari kata ombong yang merupakan bentukan lokal dari kata embun. Puncak-puncak gunung di Pulau Ambon memang sering tertutupi oleh embun yang tebal. Istilah Laha pun pernah dipakai untuk menamai Benteng Nossa Senhora de Anunciada yang menjadi cikal bakal kota. Dalam bahasa setempat, laha diartikan sebagai pelabuhan.\n" +
                    "Meskipun kini istilah Ambon mengacu pada Kota Ambon, Pulau Ambon, maupun suku Ambon, dalam perkembangan sejarah (terutama pada abad ke-20), istilah Ambon mengacu kepada penduduk Maluku Tengah. Frasa orang Ambon (Ambonezen) sendiri pun mengacu kepada para penduduk di Maluku Tengah, meskipun pada awalnya hanya digunakan untuk penduduk Kota Ambon yang memiliki budaya mestizo.",
            "Makassar sudah disebutkan dalam pupuh 14/3 kitab Nagarakretagama karya Mpu Prapanca pada abad ke-14, sebagai salah satu daerah taklukkan Majapahit. Walaupun demikian, Raja Gowa ke-9 Tumaparisi Kallonna (1510-1546) diperkirakan adalah tokoh pertama yang benar-benar mengembangkan kota Makassar. Ia memindahkan pusat kerajaan dari pedalaman ke tepi pantai, mendirikan benteng di muara Sungai Jeneberang, serta mengangkat seorang syahbandar untuk mengatur perdagangan.\n" +
                    "Pada abad ke-16, Makassar menjadi pusat perdagangan yang dominan di Indonesia Timur, sekaligus menjadi salah satu kota terbesar di Asia Tenggara. Raja-raja Makassar menerapkan kebijakan perdagangan bebas yang ketat, di mana seluruh pengunjung ke Makassar berhak melakukan perniagaan disana dan menolak upaya VOC (Belanda) untuk memperoleh hak monopoli di kota tersebut.\n" +
                    "Selain itu, sikap yang toleran terhadap agama berarti bahwa meskipun Islam semakin menjadi agama yang utama di wilayah tersebut, pemeluk agama Kristen dan kepercayaan lainnya masih tetap dapat berdagang di Makassar. Hal ini menyebabkan Makassar menjadi pusat yang penting bagi orang-orang Melayu yang bekerja dalam perdagangan di Kepulauan Maluku dan juga menjadi markas yang penting bagi pedagang-pedagang dari Eropa dan Arab.Semua keistimewaan ini tidak terlepas dari kebijaksanaan Raja Gowa-Tallo yang memerintah saat itu (Sultan Alauddin, Raja Gowa, dan Sultan Awalul Islam, Raja Tallo).\n" +
                    "Kontrol penguasa Makassar semakin menurun seiring semakin kuatnya pengaruh Belanda di wilayah tersebut dan menguatnya politik monopoli perdagangan rempah-rempah yang diterapkan Belanda melalui VOC. Pada tahun 1669, Belanda, bersama dengan La Tenri Tatta Arung Palakka dan beberapa kerajaan sekutu Belanda Melakukan penyerangan terhadap kerajaan Islam Gowa-Tallo yang mereka anggap sebagai Batu Penghalang terbesar untuk menguasai rempah-rempah di Indonesia timur. Setelah berperang habis-habisan mempertahankan kerajaan melawan beberapa koalisi kerajaan yang dipimpin oleh belanda, akhirnya Gowa-Tallo (Makassar) terdesak dan dengan terpaksa menanda tangani Perjanjian Bongaya.",
            "Kota Malang, Asal usul penamaan Malang sampai sekarang masih diperdebatkan oleh para ahli sejarah. Nama \"Malang\" muncul pertama kali pada Prasasti Pamotoh/Ukirnegara (1120 Saka/1198 Masehi) yang ditemukan pada tanggal 11 Januari 1975 oleh seorang administrator perkebunan Bantaran di Kecamatan Wlingi, Kabupaten Blitar. Dalam prasasti tembaga tersebut, tertulis salah satu bagiannya (dengan terjemahannya sebagai berikut) sebagai berikut.\n" +
                    "Malang di sini merujuk pada sebuah daerah di timur Gunung Kawi. Meskipun telah diketahui bahwa penggunaan Malang setidaknya telah berlangsung sejak abad ke-12 Masehi, tidak bisa dipastikan asal mula penamaan wilayahnya.\n" +
                    "Hipotesis pertama merujuk pada nama sebuah bangunan suci bernama Malangkuçeçwara (diucapkan [malaŋkuʃeʃworo]). Bangunan suci tersebut disebut dalam dua prasasti Raja Balitung dari Mataram Kuno, yakni Prasasti Mantyasih tahun 907 Masehi dan Prasasti 908 Masehi. Para ahli masih belum memperoleh kesepakatan di mana bangunan tersebut berada. Di satu sisi, ada sejumlah ahli yang menyebutkan bahwa bangunan Malangkuçeçwara terletak di daerah Gunung Buring, suatu pegunungan yang membujur di sebelah timur Kota Malang di mana terdapat salah satu puncaknya bernama \"Malang\". Pihak yang lain di sisi lain menduga bahwa letak sesungguhnya dari bangunan suci tersebut terdapat di daerah Tumpang, Kabupaten Malang. Di daerah tersebut, terdapat sebuah desa bernama Malangsuka, yang menurut para ahli sejarah berasal dari kata Malangkuça (diucapkan [malankuʃoː]) yang diucapkan terbalik. Pendapat ini diperkuat oleh keberadaan peninggalan-peninggalan kuno di sekitar Tumpang seperti Candi Jago dan Candi Kidal yang merupakan wilayah Kerajaan Singhasari.\n" +
                    "Nama Malangkuçeçwara terdiri atas 3 kata, yakni mala yang berarti kebatilan, kecurangan, kepalsuan, dan kejahatan, angkuça (diucapkan [aŋkuʃo]) yang berarti menghancurkan atau membinasakan, dan içwara (diucapkan [iʃworo]) yang berarti Tuhan. Oleh karena itu, Malangkuçeçwara berarti \"Tuhan telah menghancurkan yang batil\".\n" +
                    "Hipotesis kedua merujuk sebuah kisah penyerangan pasukan Kesultanan Mataram ke Malang pada 1614 yang dipimpin oleh Tumenggung Alap-Alap. Menurut cerita rakyat, terdapat sebuah percakapan antara Tumenggung Alap-Alap dengan salah satu pembantunya mengenai kondisi wilayah Malang sebelum penyerangan dimulai. Pembantu dari Tumenggung Alap-Alap tersebut menyebut warga dan prajurit dari daerah tersebut sebagai penduduk yang \"menghalang-halangi\" (malang dalam Bahasa Jawa) kedatangan dari pasukan Mataram. Setelah penaklukan tersebut, pihak Mataram menamakan daerah itu Malang.",
            "Surabaya (bahasa Jawa Kuno: Śūrabhaya) sering diartikan secara filosofis sebagai lambang perjuangan antara darat dan air. Selain itu, dari kata Surabaya juga muncul mitos pertempuran antara ikan sura / suro (ikan hiu) dan baya / boyo (buaya), yang menimbulkan dugaan bahwa terbentuknya nama \"Surabaya\" muncul setelah terjadinya pertempuran tersebut.\n" +
                    "Bukti sejarah menunjukkan bahwa Surabaya sudah ada jauh sebelum zaman kolonial, seperti yang tercantum dalam prasasti Trowulan I, berangka 1358 M. Dalam prasasti tersebut terungkap bahwa Surabaya (Churabhaya) masih berupa desa di tepi sungai Brantas dan juga sebagai salah satu tempat penyeberangan penting sepanjang daerah aliran sungai Brantas. Surabaya juga tercantum dalam pujasastra Kakawin Nagarakretagama yang ditulis oleh Empu Prapañca yang bercerita tentang perjalanan pesiar Raja Hayam Wuruk pada tahun 1365 M dalam pupuh XVII (bait ke-5, baris terakhir).\n" +
                    "Walaupun bukti tertulis tertua mencantumkan nama Surabaya berangka tahun 1358 M (Prasasti Trowulan) dan 1365 M (Nagarakretagama), para ahli menduga bahwa wilayah Surabaya sudah ada sebelum tahun-tahun tersebut. Menurut pendapat budayawan Surabaya berkebangsaan Jerman Von Faber, wilayah Surabaya didirikan tahun 1275 M oleh Raja Kertanegara sebagai tempat permukiman baru bagi para prajuritnya yang berhasil menumpas pemberontakan Kemuruhan pada tahun 1270 M. Pendapat yang lainnya mengatakan bahwa Surabaya dahulu merupakan sebuah daerah yang bernama Ujung Galuh.\n" +
                    "Versi lain menyebutkan, Surabaya berasal dari cerita tentang perkelahian hidup-mati antara Adipati Jayengrono dan Sawunggaling. Konon, setelah mengalahkan pasukan Kekaisaran Mongol utusan Kubilai Khan atau yang dikenal dengan pasukan Tartar, Raden Wijaya mendirikan sebuah keraton di daerah Ujung Galuh dan menempatkan Adipati Jayengrono untuk memimpin daerah itu. Lama-lama karena menguasai ilmu buaya, Jayengrono semakin kuat dan mandiri sehingga mengancam kedaulatan Kerajaan Majapahit. Untuk menaklukkan Jayengrono, maka diutuslah Sawunggaling yang menguasai ilmu sura.\n" +
                    "Adu kesaktian dilakukan di pinggir Kali Mas, di wilayah Peneleh. Perkelahian itu berlangsung selama tujuh hari tujuh malam dan berakhir dengan tragis, karena keduanya meninggal setelah kehilangan tenaga.\n" +
                    "Nama Śūrabhaya sendiri dikukuhkan sebagai nama resmi pada abad ke-14 oleh penguasa Ujung Galuh, Arya Lêmbu Sora.",
            "Asal usul nama Palembang mempunyai beberapa versi. Salah satu versi mengaitkan Palembang dengan kata dalam bahasa Jawa, \"limbang\", yang berarti membersihkan biji atau logam dari tanah atau benda-benda luar lain. Pemisahan dilakukan dengan bantuan alat berupa keranjang kecil untuk mengayak tanah berkandungan logam atau biji di aliran sungai. \"Pa\" adalah kata depan yang dipakai orang Jawa untuk menunjuk suatu tempat berlangsungnya usaha atau keadaan. Versi ini terkait erat dengan peran Palembang pada masa lalu sebagai tempat mencuci emas dan biji timah. Versi lain menghubungkan Palembang dengan kata \"lemba\", yang berarti tanah yang dihanyutkan air ke tepi.\n" +
                    "Kota ini dianggap sebagai salah satu pusat dari kerajaan Sriwijaya, Serangan Rajendra Chola dari Kerajaan Chola pada tahun 1025, menyebabkan kota ini hanya menjadi pelabuhan sederhana yang tidak berarti lagi bagi para pedagang asing.\n" +
                    "Selanjutnya berdasarkan kronik Tiongkok nama Pa-lin-fong yang terdapat pada buku Chu-fan-chi yang ditulis pada tahun 1178 oleh Chou-Ju-Kua dirujuk kepada Palembang.\n" +
                    "Berdasarkan kisah Kidung Pamacangah dan Babad Arya Tabanan disebutkan seorang tokoh dari Kediri yang bernama Arya Damar sebagai bupati Palembang turut serta menaklukan Bali bersama dengan Gajah Mada Mahapatih Majapahit pada tahun 1343.\n" +
                    "Pada awal abad ke-15, kota Palembang diduduki perompak Chen Zuyi yang berasal dari Tiongkok. Armada bajak laut Chen Zuyi kemudian ditumpas oleh Laksamana Cheng Ho pada tahun 1407.\n" +
                    "Kemudian sekitar tahun 1513, Tomé Pires seorang apoteker Portugis menyebutkan Palembang, telah dipimpin oleh seorang patih yang ditunjuk dari Jawa yang kemudian dirujuk kepada kesultanan Demak serta turut serta menyerang Malaka yang waktu itu telah dikuasai oleh Portugis.\n" +
                    "Palembang muncul sebagai kesultanan pada tahun 1659 dengan Sri Susuhunan Abdurrahman sebagai raja pertamanya. Namun pada tahun 1823 kesultanan Palembang dihapus oleh pemerintah Hindia Belanda. Setelah itu Palembang dibagi menjadi dua keresidenan besar dan permukiman di Palembang dibagi menjadi daerah Ilir dan Ulu.",
            "Yogyakarta terambil dari dua kata, yaitu Ayogya atau Ayodhya yang berarti \"kedamaian\" (atau tanpa perang, a \"tidak\", yogya merujuk pada yodya atau yudha, yang berarti \"perang\"), dan Karta yang berarti \"baik\". Ayodhya merupakan kota yang bersejarah di India di mana wiracarita Ramayana terjadi. Tapak keraton Yogyakarta sendiri menurut babad (misalnya Babad Giyanti) dan leluri (riwayat oral) telah berupa sebuah dalem yang bernama Dalem Gerjiwati; lalu dinamakan ulang oleh Sunan Pakubuwana II sebagai Dalem Ayogya.",
            "Kota Medan Pada zaman dahulu dikenal dengan nama Tanah Deli dan keadaan tanahnya berawa-rawa kurang lebih seluas 4000 Ha. Beberapa sungai melintasi Kota Medan ini dan semuanya bermuara ke Selat Malaka. Sungai-sungai itu adalah Sei Deli, Sei Babura, Sei Sikambing, Sei Denai, Sei Putih, Sei Badra, Sei Belawan dan Sei Sulang Saling/Sei Kera.\n" +
                    "Dalam buku The History of Medan tulisan Tengku Luckman Sinar (1991), dituliskan bahwa menurut \"Hikayat Aceh\", Medan sebagai pelabuhan telah ada pada tahun 1590, dan sempat dihancurkan selama serangan Sultan Aceh Alauddin Saidi Mukammil kepada Raja Haru yang berkuasa di situ. Serangan serupa dilakukan Sultan Iskandar Muda tahun 1613, terhadap Kesultanan Deli. Sejak akhir abad ke-16, nama Haru berubah menjadi Ghuri, dan akhirnya pada awal abad ke-17 menjadi Deli. Pertempuran terus-menerus antara Haru dengan Aceh mengakibatkan penduduk Haru jauh berkurang. Sebagai daerah taklukan, banyak warganya yang dipindahkan ke Aceh untuk dijadikan pekerja kasar.\n" +
                    "Selain dengan Aceh, Kerajaan Haru yang makmur ini juga tercatat sering terlibat pertempuran dengan Kerajaan Melayu di Semenanjung Malaka dan juga dengan kerajaan dari Jawa. Serangan dari Pulau Jawa ini antara lain tercatat dalam kitab Pararaton yang dikenal dengan Ekspedisi Pamalayu. Dalam Negarakertagama, Mpu Prapanca juga menuliskan bahwa selain Pane (Panai), Majapahit juga menaklukkan Kampe (Kampai) dan Harw (Haru). Berkurangnya penduduk daerah pantai timur Sumatra akibat berbagai perang ini, lalu diikuti dengan mulai mengalirnya suku-suku dari dataran tinggi pedalaman turun ke pesisir pantai timur Sumatra. Suku Karo bermigrasi ke daerah pantai Langkat, Serdang, dan Deli. Suku Simalungun ke daerah pantai Batubara dan Asahan, serta suku Mandailing ke daerah pantai Kualuh, Kota Pinang, Panai, dan Bilah."
    };

    private static int[] kotaImages = {
            R.drawable.jakarta,
            R.drawable.bali,
            R.drawable.banjarmasin,
            R.drawable.ambon,
            R.drawable.makassar,
            R.drawable.malang,
            R.drawable.surabaya,
            R.drawable.palembang,
            R.drawable.yogyakarta,
            R.drawable.medan
    };

    static ArrayList<Kota> getListData(){
    ArrayList<Kota> list = new ArrayList<>();
    for (int position = 0; position<kotaNames.length;position++){
        Kota kota = new Kota();
        kota.setNamaKota(kotaNames[position]);
        kota.setDetailKota(kotaDetails[position]);
        kota.setPhotoKota(kotaImages[position]);
        list.add(kota);
    }
    return list;
    }


}
